### ISSUE TITLE
jQuery.Deferred exception

### ISSUE THREAD

**Issue by rofiuddin15** [ColorlibHQ/AdminLTE#1704]
jQuery.Deferred exception: Chart is not defined ReferenceError: Chart is not defined
 at HTMLDocument.<anonymous> (file:///home/rofiareiv/Downloads/AdminLTE-2.4.2/dist/js/pages/dashboard2.js:17:26)
    at j (file:///home/rofiareiv/Downloads/AdminLTE-2.4.2/bower_components/jquery/dist/jquery.min.js:2:29999)
    at k (file:///home/rofiareiv/Downloads/AdminLTE-2.4.2/bower_components/jquery/dist/jquery.min.js:2:30313) undefined

**Comment by bellwood** [comment]
Have you added the `<script>` tag to load the chartjs resource to your project?

If so, could you please share your markup of how you are utilizing it?
