### ISSUE TITLE
please fix it. jquery-ui have a bug with jquery 3.2.1

### ISSUE THREAD

**Issue by hhniao** [ColorlibHQ/AdminLTE#1731]
`Uncaught TypeError: elem.getClientRects is not a function
    at jQuery.fn.init.offset (http://localhost/projects/backend/web/assets/1ac0d9f5/jquery.js:9984:14)
    at Object.getWithinInfo (http://localhost/projects/backend/web/assets/3f1b7a61/jquery-ui.js:971:26)
    at jQuery.fn.init.$.fn.position (http://localhost/projects/backend/web/assets/3f1b7a61/jquery-ui.js:993:23)
    at $.(anonymous function).(anonymous function)._suggest (http://localhost/projects/backend/web/assets/3f1b7a61/jquery-ui.js:2494:6)
    at $.(anonymous function).(anonymous function)._suggest (http://localhost/projects/backend/web/assets/3f1b7a61/jquery-ui.js:415:25)
    at $.(anonymous function).(anonymous function).__response (http://localhost/projects/backend/web/assets/3f1b7a61/jquery-ui.js:2438:9)
    at $.(anonymous function).(anonymous function).__response (http://localhost/projects/backend/web/assets/3f1b7a61/jquery-ui.js:415:25)
    at $.(anonymous function).(anonymous function)._superApply (http://localhost/projects/backend/web/assets/3f1b7a61/jquery-ui.js:405:36)
    at $.(anonymous function).(anonymous function).__response (http://localhost/projects/backend/web/assets/3f1b7a61/jquery-ui.js:2592:8)
    at $.(anonymous function).(anonymous function).__response (http://localhost/projects/backend/web/assets/3f1b7a61/jquery-ui.js:415:25)
ui-bg_glass_75_dadada_1x400.png Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by hhniao** [comment]
update jquery-ui to 1.12.4 will fix this bug

**Comment by dvdobrovolskiy** [comment]
1.12.1 din`t help to me

**Comment by SowmyaManohar** [comment]
@dvdobrovolskiy : any luck solving this? am also using the same version and getting the same error
