### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dai19470** [ColorlibHQ/AdminLTE#2627]
**Describe the bug**
当我使用vue构建的时候，引入admin-lte报错，错误如下
![image](https://user-images.githubusercontent.com/21135250/78145024-f688d100-7462-11ea-95ea-453ac04e3319.png)
 
`
 ERROR  Failed to compile with 1 errors                                                                               21:43:25

 error  in ./node_modules/admin-lte/dist/css/adminlte.min.css

Module build failed: BrowserslistError: Unknown browser query `dead`
    at /home/david/workspace/web/demo_adminlte/node_modules/browserslist/index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (/home/david/workspace/web/demo_adminlte/node_modules/browserslist/index.js:132:18)
    at browserslist (/home/david/workspace/web/demo_adminlte/node_modules/browserslist/index.js:224:16)
    at Browsers.parse (/home/david/workspace/web/demo_adminlte/node_modules/autoprefixer/lib/browsers.js:61:16)
    at new Browsers (/home/david/workspace/web/demo_adminlte/node_modules/autoprefixer/lib/browsers.js:52:30)
    at loadPrefixes (/home/david/workspace/web/demo_adminlte/node_modules/autoprefixer/lib/autoprefixer.js:70:24)
    at plugin (/home/david/workspace/web/demo_adminlte/node_modules/autoprefixer/lib/autoprefixer.js:81:24)
    at LazyResult.run (/home/david/workspace/web/demo_adminlte/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.asyncTick (/home/david/workspace/web/demo_adminlte/node_modules/postcss/lib/lazy-result.js:192:32)
    at LazyResult.asyncTick (/home/david/workspace/web/demo_adminlte/node_modules/postcss/lib/lazy-result.js:204:22)
    at /home/david/workspace/web/demo_adminlte/node_modules/postcss/lib/lazy-result.js:197:27

 @ ./node_modules/admin-lte/dist/css/adminlte.min.css 4:14-131 13:3-17:5 14:22-139
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

`
**版本信息**
  npm: '6.13.4',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.3',
  icu: '64.2',
  llhttp: '2.0.4',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.16.1',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.0',
  v8: '7.8.279.23-node.31',
  zlib: '1.2.11'

**依赖版本**
 "admin-lte": "^3.0.2",
    "bootstrap": "^4.4.1",
    "jquery": "^3.4.1",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1"

**Comment by REJack** [comment]
Please use the bug report template and write the issue in english otherwise I can't help.
