### ISSUE TITLE
[BUG] Update error

### ISSUE THREAD

**Issue by dima-bzz** [ColorlibHQ/AdminLTE#2631]
**Describe the bug**
When I try to upgrade to 3.0.4 I get this error.

```
> admin-lte@3.0.4 install .../node_modules/admin-lte
> npm run plugins


> admin-lte@3.0.4 plugins .../node_modules/admin-lte
> node build/npm/Publish.js -v

.../node_modules/admin-lte/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.../node_modules/admin-lte/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```
**Environment (please complete the following information):**
 - Operating System:  [Ubuntu]

**Comment by REJack** [comment]
Which Node Version you use?

**Comment by dima-bzz** [comment]
8.10.0

**Comment by renwarkurd** [comment]
same problem here

```
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> admin-lte@3.0.4 install D:\projects\myProject\node_modules\admin-lte
> npm run plugins


> admin-lte@3.0.4 plugins D:\projects\myProject\node_modules\admin-lte
> node build/npm/Publish.js -v

D:\projects\myProject\node_modules\fs-extra\lib\mkdirs\make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\projects\myProject\node_modules\fs-extra\lib\mkdirs\index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! admin-lte@3.0.4 plugins: `node build/npm/Publish.js -v`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-lte@3.0.4 plugins script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by renwarkurd** [comment]
I fixed it, by installing latest version node.
Node v12.16.1
npm v6.14.2

**Comment by REJack** [comment]
I added a note according to this requirement.

> Note: To install it via NPM/Yarn, you need at least Node.js 10 or higher.
