### ISSUE TITLE
admin lte css import problem 

### ISSUE THREAD

**Issue by rumman9** [ColorlibHQ/AdminLTE#3023]
plugin (F:\xmp\htdocs\2020\vue_api\node_modules\autoprefixer\lib\autoprefixer.js:81:24)      
    at LazyResult.run (F:\xmp\htdocs\2020\vue_api\node_modules\postcss\lib\lazy-result.js:277:20)   
    at LazyResult.asyncTick (F:\xmp\htdocs\2020\vue_api\node_modules\postcss\lib\lazy-result.js:192:32)
    at LazyResult.asyncTick (F:\xmp\htdocs\2020\vue_api\node_modules\postcss\lib\lazy-result.js:204:22)
    at F:\xmp\htdocs\2020\vue_api\node_modules\postcss\lib\lazy-result.js:197:27

 @ ./node_modules/admin-lte/dist/css/adminlte.min.css 4:14-131 13:3-17:5 14:22-139
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/dashbord/admin-master.vue
 @ ./src/views/dashbord/admin-master.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js

**Comment by REJack** [comment]
I need to know how you import the scss file & build the css files. Also I cant really see whats the error is the error log complete?
