### ISSUE TITLE
[BUG] npm install : compilation failed

### ISSUE THREAD

**Issue by adonix-dev** [ColorlibHQ/AdminLTE#3371]
**Describe the bug**
npm install gives a compilation error

**To Reproduce**
1. git clone
2. remove package-lock
3. npm install

**Environment (please complete the following information):**
- AdminLTE Version: Last (git clone)
- Operating System:  CentOS 7 (Linux 3.10.0-1062.9.1.el7.x86_64)
- Browser (Version): N/A

**Debug Info**
1. Debug Log File 
[npm-debug.log](https://github.com/ColorlibHQ/AdminLTE/files/5901061/npm-debug.log)
2. Console Extract
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN prefer global node-gyp@7.1.2 should be installed with -g

> node-sass@5.0.0 install /root/AdminLTE/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-48_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@5.0.0 postinstall /root/AdminLTE/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /root/AdminLTE/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/root/AdminLTE/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@7.1.2
gyp info using node@6.17.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.6.8"
gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 6.17.1
gyp verb command install [ '6.17.1' ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack /root/AdminLTE/node_modules/tar/node_modules/mkdirp/lib/opts-arg.js:7
gyp ERR! stack     opts = { mode: 0o777, fs, ...opts }
gyp ERR! stack                               ^^^
gyp ERR! stack
gyp ERR! stack SyntaxError: Unexpected token ...
gyp ERR! stack     at createScript (vm.js:56:10)
gyp ERR! stack     at Object.runInThisContext (vm.js:97:10)
gyp ERR! stack     at Module._compile (module.js:549:28)
gyp ERR! stack     at Object.Module._extensions..js (module.js:586:10)
gyp ERR! stack     at Module.load (module.js:494:32)
gyp ERR! stack     at tryModuleLoad (module.js:453:12)
gyp ERR! stack     at Function.Module._load (module.js:445:3)
gyp ERR! stack     at Module.require (module.js:504:17)
gyp ERR! stack     at require (internal/module.js:20:19)
gyp ERR! stack     at Object.<anonymous> (/root/AdminLTE/node_modules/tar/node_modules/mkdirp/index.js:1:79)
gyp ERR! System Linux 3.10.0-1062.9.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/root/AdminLTE/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/AdminLTE/node_modules/node-sass
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
Build failed with error code: 7
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @rollup/plugin-babel@5.2.3 requires a peer of @types/babel__core@^7.1.9 but none was installed.
npm WARN bootstrap-switch@3.3.4 requires a peer of bootstrap@^3.1.1 but none was installed.
npm WARN tempusdominus-bootstrap-4@5.39.0 requires a peer of tempusdominus-core@5.19.0 but none was installed.
npm WARN ws@7.4.2 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.4.2 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm ERR! Linux 3.10.0-1062.9.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@5.0.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@5.0.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/AdminLTE/npm-debug.log
```

**Comment by danny007in** [comment]
https://github.com/ColorlibHQ/AdminLTE/issues/3288 check plz

**Comment by REJack** [comment]
You need at least node v10, you use v6. I recommend node LTS (v14).
