### ISSUE TITLE
[BUG] JS error Cannot read properties of undefined (reading 'classList')

### ISSUE THREAD

**Issue by lenamtl** [ColorlibHQ/AdminLTE#4514]
Hi,

I found a JS error on  https://adminlte.io/themes/v3/pages/layout/top-nav.html
Open browser console 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at demo.js:136:22
    at demo.js:175:114
```

**Comment by REJack** [comment]
Fixed with c2d7f21a334887447b52bbafd945b9df7cd33e12
