### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ybzc-gg** [ColorlibHQ/AdminLTE#4518]
**Describe the bug**
$('.content-wrapper').IFrame('createTab', 'Home', 'index.html, 'index', true) NOT WORK

**To Reproduce**
1. Go to iframe.html under root dir after discompose
2. parse above code ending the html body
3. open iframe.html
4. See error on chrome dev consle->>>>>>>>>>>>>>>>>>>>>>>>>>
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'lte.iframe' closes the circle
    at JSON.stringify (<anonymous>)
    at S.fn.init._jQueryInterface [as IFrame] (IFrame.js:424:60)
    at IFrame.js:445:27
    at dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)

**Expected behavior**
I want open  a link from an iframe, but I got this error

**Screenshots**

**Environment (please complete the following information):**
- AdminLTE Version: 3.2.0
- Operating System:  windows chrome 
- Browser (Version): Chrome 100+

**Additional context**
Just the templete

**Comment by REJack** [comment]
Fixed with 75deb497b39c1a8547fe0f21a2478b066b223396
Thanks for the idea with your modified _jQueryInterface 😄 

It would be nice if you can test the changes, but you will need to generate the new dist files.

**Comment by iwasthesword** [comment]
is there a plan to add a new release with these changes? do I need to build this myself? I'm having the same problem but I'm using the `dist` version and couldn't find an updated one

**Comment by ybzc-gg** [comment]
I'm not a collaborator of this repository so I can not do release action,
but you could build from master branch by yourself

**Comment by iwasthesword** [comment]
> I'm not a collaborator of this repository so I can not do release action, but you could build from master branch by yourself

Hey, thanks! I was having problems building it myself on windows, but managed to get it working on linux.

**Comment by ybzc-gg** [comment]
sorry to late to reply, you can use these files i built before it match
version 3.2

https://drive.google.com/file/d/1-5uspwBh9XPgS9gHB2Y7CECXtnHZpEk4/view?usp=share_link
